// build-themes.mjs — turn themes-design.json (agent output) into
// src/styles/themes-generated.css and src/scripts/themes-extra.js.
// Usage: node scripts/build-themes.mjs

import { readFileSync, writeFileSync } from 'fs';

const designs = JSON.parse(readFileSync('themes-design.json', 'utf8'));

const VAR_MAP = {
  bg: '--bg', bg2: '--bg-2', panel: '--panel', border: '--border',
  borderSoft: '--border-soft', cream: '--cream', teal: '--teal', terra: '--terra',
  violet: '--violet', text: '--text', textDim: '--text-dim', textFaint: '--text-faint',
  glass: '--glass',
};
const FONT_MAP = { display: '--display', serif: '--serif', sans: '--sans', mono: '--mono' };

let css = `/* themes-generated.css — agent-designed theme packs (build-themes.mjs) */\n`;
const jsEntries = [];

for (const t of designs) {
  css += `\n/* ---- ${t.name}: ${t.blurb} ---- */\n[data-theme="${t.id}"] {\n`;
  for (const [k, v] of Object.entries(t.vars)) {
    if (VAR_MAP[k]) css += `  ${VAR_MAP[k]}: ${v};\n`;
  }
  for (const [k, v] of Object.entries(t.fonts)) {
    if (FONT_MAP[k]) css += `  ${FONT_MAP[k]}: ${v};\n`;
  }
  css += `}\n${t.extraCSS.trim()}\n`;

  jsEntries.push(`  {
    id: ${JSON.stringify(t.id)}, name: ${JSON.stringify(t.name)}, blurb: ${JSON.stringify(t.blurb)},
    dark: ${t.dark}, swatches: ${JSON.stringify(t.swatches)},
    fill: ${parseInt(t.fill.slice(1), 16)}, grid: [${t.grid.map((g) => parseInt(g.slice(1), 16)).join(', ')}],
    tags: {
${Object.entries(t.tags).map(([k, v]) => `      ${k}: ${parseInt(v.slice(1), 16)},`).join('\n')}
    },
  },`);
}

writeFileSync('src/styles/themes-generated.css', css);
writeFileSync('src/scripts/themes-extra.js', `// themes-extra.js — agent-designed theme packs (generated by build-themes.mjs).
import { registerThemes } from './themes.js';

registerThemes([
${jsEntries.join('\n')}
]);
`);
console.log(`built ${designs.length} themes: ${designs.map((d) => d.id).join(', ')}`);
